name: Tests
on:
  push:
    branches:
      - develop
      - master
jobs:
  checks:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Runs tests
      uses: cedrickring/golang-action/go1.15@1.6.0
      with:
        args: make test